"""
ReportModule — GhostRecon module.
"""
import re
import time
import urllib.parse

try:
    import requests
    from requests.exceptions import RequestException
except ImportError:
    requests = None

from modules import BaseModule


class ReportModule(BaseModule):
    NAME = "Reporter"

    def run(self):
        pass  # Called explicitly from session._save_results()

    def build_report(self):
        from datetime import datetime
        findings = self.db.findings
        target   = self.target
        now      = datetime.now().strftime("%Y-%m-%d %H:%M")

        def sev_count(s):
            return len([f for f in findings if f["severity"] == s])

        sev_order = ["critical", "high", "medium", "low", "info"]
        sorted_findings = sorted(findings, key=lambda f: sev_order.index(f["severity"])
                                 if f["severity"] in sev_order else 5)

        md  = f"# Bug Bounty Report — {target}\n"
        md += f"**Date:** {now}  \n"
        md += f"**Tool:** GhostRecon v3.0 by Nishant 👻  \n"
        md += f"**Total Findings:** {len(findings)}\n\n---\n\n"

        md += "## Executive Summary\n\n"
        md += (
            f"Security assessment of `{target}` identified **{len(findings)} vulnerabilities**: "
            f"{sev_count('critical')} Critical, {sev_count('high')} High, "
            f"{sev_count('medium')} Medium, {sev_count('low')} Low. "
        )
        if sev_count("critical") > 0:
            md += "**Immediate remediation is required for critical findings.**\n\n"
        md += "\n---\n\n"

        md += "## Severity Summary\n\n"
        md += "| Severity | Count |\n|----------|-------|\n"
        for s in sev_order:
            emoji = {"critical":"🔴","high":"🟠","medium":"🟡","low":"🟢","info":"ℹ️"}.get(s,"")
            md += f"| {emoji} {s.capitalize()} | {sev_count(s)} |\n"
        md += "\n---\n\n"

        md += "## Findings\n\n"
        for i, f in enumerate(sorted_findings, 1):
            md += f"### {i}. [{f['severity'].upper()}] {f['title']}\n\n"
            md += f"**URL:** `{f['url']}`  \n"
            if f.get("cvss"):
                md += f"**CVSS Score:** {f['cvss']}  \n"
            md += f"**Module:** {f['module']}  \n"
            md += f"**Confidence:** {f.get('confidence','N/A')}  \n\n"
            md += f"**Description:**  \n{f['description']}\n\n"
            if f.get("evidence"):
                md += "**Evidence:**\n"
                for ev in f["evidence"]:
                    md += f"- {ev}\n"
                md += "\n"
            md += f"**Remediation:**  \n{f['remediation']}\n\n"
            if f.get("references"):
                md += "**References:**\n"
                for ref in f["references"]:
                    md += f"- {ref}\n"
                md += "\n"
            md += "---\n\n"

        # XSS PoCs
        xss_pocs = self.ctx.get("xss_pocs", [])
        if xss_pocs:
            md += "## XSS Proof of Concept URLs\n\n"
            for poc in xss_pocs:
                md += f"- **Param:** `{poc['param']}` | **Context:** {poc['context']}  \n"
                md += f"  PoC: `{poc['poc_url']}`\n\n"

        # SQLi findings
        sqli = self.ctx.get("sqli_findings", [])
        if sqli:
            md += "## SQL Injection Details\n\n"
            for s in sqli:
                md += (f"- **Param:** `{s['param']}` | **Technique:** {s['technique']} | "
                       f"**DB:** {s['db_type']}  \n")
                md += f"  Payload: `{s['payload']}`\n\n"

        md += "\n---\n*Report generated by GhostRecon v3.0 — Crafted with care by Nishant 👻*\n"
        return md
